# Generated by Django 5.1 on 2024-08-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='alt',
        ),
    ]
