# Generated by Django 5.0.6 on 2024-06-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
