# Generated by Django 5.0.6 on 2024-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default-avatar.jpg', upload_to='user-avatars/'),
        ),
    ]
