# Generated by Django 5.0.6 on 2024-06-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='DishPriceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.CharField(choices=[('instock', 'In stock'), ('notavailable', 'Not available')], default='instock', max_length=31)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurants',
            field=models.ManyToManyField(through='menu.DishPriceAvailability', to='menu.restaurant'),
        ),
    ]
