# Generated by Django 5.0.6 on 2024-07-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_text_review_comment_alter_dish_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('salads', 'Salads'), ('soups', 'Soups'), ('sidedishes', 'Side dishes'), ('desserts', 'Desserts'), ('softdrinks', 'Soft drinks'), ('alcohol', 'Alcohol')], max_length=31),
        ),
    ]
