# Generated by Django 5.0.6 on 2024-06-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_dish_restaurant_dishpriceavailability_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishPriceAvailability',
            new_name='RestaurantDish',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='restaurant_dish',
            new_name='dish',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant'),
            preserve_default=False,
        ),
    ]
