# Generated by Django 5.1 on 2024-08-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dish_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='photo',
            new_name='image',
        ),
    ]
