# Generated by Django 5.0.6 on 2024-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_dishpriceavailability_restaurantdish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantdish',
            unique_together={('restaurant', 'dish')},
        ),
    ]
