# Generated by Django 5.1 on 2024-08-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_photo_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
