# Generated by Django 5.0.6 on 2024-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_name_alter_restaurantdish_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
