# Generated by Django 5.0.6 on 2024-06-29 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/default-dish.jpg', upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='restaurantdish',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('notavailable', 'Not available')], default='available', max_length=31),
        ),
        migrations.AlterField(
            model_name='restaurantdish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='The price cannot be negative.')]),
        ),
    ]
