# Generated by Django 5.1 on 2024-08-23 13:00

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=i18nfield.fields.I18nTextField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=i18nfield.fields.I18nCharField(max_length=100, unique=True),
        ),
    ]
